Repository legesher/legesher, pull requests merged in 2019-10, with the labels that each got.

#59 docs: add legesher-pride repo to readme [ci skip]
  README.md
Labels: Hacktoberfest

#60 add linting ESLint and Prettier
  .eslintrc
  .prettierrc
  index.js
  lib/legesher-view.js
  lib/legesher.js
  lib/tree-sitter/python/python-grammar-template.js
  menus/legesher.json
  package-lock.json
  package.json
  spec/legesher-spec.js
  spec/legesher-view-spec.js
Labels: Hacktoberfest

#61 feat: Add all contributors
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: 💼 Opportunity: Business

#66 Add language conventions
  LANGUAGE_CONVENTIONS.md
  README.md
Labels: 📆 Opportunity: Project Management

#67 Fix misspelled word
  CONTRIBUTING.md
Labels: 🖋 Opportunity: Content

#68 Add all contributors from Legesher project
  community/README.md
  community/all-contributorsrc
Labels: 🚧 Opportunity: Maintenance

#69 Update pull-request.md
  .github/ISSUE_TEMPLATE/pull-request.md
Labels: Hacktoberfest, 📆 Opportunity: Project Management
